### ISSUE TITLE
IdentityUI toolbar covering buttons

### ISSUE THREAD

**Issue by axldyb** [schibsted/account-sdk-ios#106]
When testing the IdentityUI I find that a toolbar appears at the bottom when typing in the username and passwords textfields. Is this intensional? It covers up the continue/forgot password buttons and also adds a toolbar button for continue. Did I forgot to configure something?

### Screenshots
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1060670/40113917-51e76c3e-590b-11e8-9d67-502ed5d0f207.png">        <img width="300" alt="image" src="https://user-images.githubusercontent.com/1060670/40113924-55cc4f9a-590b-11e8-8b58-a0a3ab273782.png">

**Comment by aliak00** [comment]
Is this in the simulator? Cause then it might just be that you have toggle software keyboard disabled, so the simulator just shows the toolbar there. On a device this should not be happening though, in which case it'd be a bug somewhere.

**Comment by aliak00** [comment]
Ya, 108 fixes bug where keyboard was not going back down. Simulator showing the toolbar when software keyboard is toggled is simulator default behavior though.

About UX: what do you suggest?

**Comment by axldyb** [comment]
How about having the buttons just below the textfield and not pushing them all the way down to the bottom? 

A more dynamic solution could be to animate the textfield and the button (especially the continue button) into the view when the textfield becomes active. Instagram does something like that :) This way we don't need the toolbar and can have only one way to proceed to the next step.

**Comment by aliak00** [comment]
Sounds snazzy :) The less ways to proceed the better so having one certainly sounds nice. If there's a version 5 of the UX (we're on 4 now) then maybe the UX guys can take this in to consideration!

@mela124 some feedback for Jonas me thinks 👆 

I'll close this issue for now though since the main thing is ok I guess? You can open again if it seems like we didn't catch the bug!
