### ISSUE TITLE
Cancelling the terms screen keeps user logged in. (ref. #102)

### ISSUE THREAD

**Issue by axldyb** [schibsted/account-sdk-ios#135]
I opened an issue on this earlier (#102) but I'm still seing this issue in rc6. I'm not allowed to reopen #102 so I'm posting a new one. 

Original issue:
> When implementing the SDK in my project I get an issue using the login UI. After the password is entered and the continue button is pressed I see the terms screen. When tapping the cancel button (the X in the top right corner) the callback claims the login was cancelled. However, when checking the identityManager.currentUser.state the user seems to be logged in.

I'm keeping a reference to the same `identityManager` around and the next time I try to present the IdentityUI the user is still logged in. I have a dirty workaround at the moment calling `identityManager.currentUser.logout()` if the result of the flow is cancelled.

**Comment by aliak00** [comment]
Do you need to store the `identityManager` btw? If you only have login with UIs then the end of the login process gives you a `User` object after which you can set up your delegates and go from there -  no need for logout hack then. Does that work?

**Comment by axldyb** [comment]
At the moment I have the IdentityManager as a lazy var. After seeing how it is done in the example project (it is stored as a let, hence initialized once) I though this was how it was supposed to be. I also need to check the current login status and from the same example project I see that it is done this way: `identityManager.currentUser.state == .loggedIn`. I can't find that a reference to the user is keep after using the IdentityUI. Might be that I misunderstand the intended usage, but then I might be confused by the examples.

**Comment by aliak00** [comment]
The example UI shows headless and visual login so is probably doing more than a few things an only-UI-login app doesn't need to. 

`IdentityManager.currentUser.state == .loggedIn` can be used at start up to see if a `User` was found in the keychain. If not, after you start the `IdentityUI` the callback `didFinish` gives you back a `User` which can be saved as an instance.

So:
```
if identityManager.currentUser.state == .loggedIn {
  yourGlobalUserObject = identityManager.currentUser
}

// Then somewhere else where you need a user object
guard yourGlobalUserObject?.state == .loggedIn else {
  identityUI.presentBlahBlah(...)
}

// And your delegate:
  func didFinish(result: IdentityUIResult) {
    // ...
    case let .completed(user):
    yourGlobalUserObject = user
  }
```

**Comment by axldyb** [comment]
Alright, I might need to do some refactoring of my setup then. Thanks!
