### ISSUE TITLE
Show correct error message for short password

### ISSUE THREAD

**Issue by mela124** [schibsted/account-sdk-ios#190]
When creating an account, if the password is less than 8 characters, we should show the error message:

`Your password should have at least 8 characters.`

Localization:
Swedish: Ditt lösenord måste ha minst 8 tecken.
Norwegian: Passordet ditt skal ha minst 8 tegn.
Finnish: Salasanassa tulee olla vähintään 8 merkkiä.

**Comment by aliak00** [comment]
Fixed with #193
