### ISSUE TITLE
Missing User+load.swift file from release versions

### ISSUE THREAD

**Issue by mbmadaj** [schibsted/account-sdk-ios#227]
In the documentation a suggested way to 

> Check if you already have a user

is

```
Get the last user that was logged in with the SDK

let user = User.loadLast(clientConfiguration: .default);
user.delegate = //...
switch user.state {
case .loggedIn:
    // Yay, carry on with app
case .loggedOut:
    // Ok, fire up the IdentityUI
}
```

However the [file User+load.swift](https://github.com/schibsted/account-sdk-ios/blob/master/Source/Manager/User/User%2Bload.swift) does not appear to be part of release 1.0.4 or 1.1.0. Unfortunately the method used in this extension is not available outside the lib scope so without changing source files not much can be done on client side to follow documentation.

**Comment by aliak00** [comment]
Hi!

The file in question is in master and not in any of the releases. The documentation you are quoting from is also master's readme and not the linked documentation to the current tagged release -> [here](https://schibsted.github.io/account-sdk-ios/)

`User+load.swift` should make it in to the next minor release :)
