### ISSUE TITLE
modal presentation style of identity ui when compiled with iOS 13.x sdk

### ISSUE THREAD

**Issue by robertmusialek** [schibsted/account-sdk-ios#280]
according to the documentation `modalPresentationStyle` behaviour changed:

> Defaults to UIModalPresentationAutomatic on iOS starting in iOS 13.0, and UIModalPresentationFullScreen on previous versions.
By default UIViewController resolves UIModalPresentationAutomatic to UIModalPresentationPageSheet, but other system-provided view controllers may resolve UIModalPresentationAutomatic to other concrete presentation styles.

because of this change when compiled with xcode 11 and iOS 13, IdentityUI is presented in a way that it makes it possible to dismiss by swiping down, even if `isCancelable` is set to false

![IMG_0D5A3D4ABE4F-1](https://user-images.githubusercontent.com/14923387/66039508-61d60280-e515-11e9-946a-e224ad2e60db.jpeg)
![IMG_CE13BA07BC23-1](https://user-images.githubusercontent.com/14923387/66039520-6995a700-e515-11e9-9669-34e054f22a4a.jpeg)

possible fixes include changing presentation style to `.fullScreen` or disabling swipe gesture when presented modally by setting `isModalInPresentation` to true
it might be good idea to tie this to `isCancelable` parameter of IdentityUI?

those changes also have implications on close/save/dismiss type of buttons on modal presentation of view controllers, here's great article that explains everything:
https://medium.com/@hacknicity/view-controller-presentation-changes-in-ios-13-ac8c901ebc4e

**Comment by zamzterz** [comment]
Thanks for the detailed report and references! 🙇 

I think it's better to just disable swipe gesture if the flow isn't cancellable; there's no need for our login flow to be full screen. 🙂
