### ISSUE TITLE
Link button customization possibility

### ISSUE THREAD

**Issue by pauliusef** [schibsted/account-sdk-ios#290]
Wondering if there is a possibility to customize the styling (color) of the "link" button (blue in the screenshot below)? Using latest release of the SDK.

![image](https://user-images.githubusercontent.com/5462512/68671297-ae225280-0557-11ea-952f-589686cf1cd0.png)

**Comment by zamzterz** [comment]
That is currently supported.

**Comment by pauliusef** [comment]
Would it be possible to expand in couple of sentences, where to look for the customization of the color for this exact label? No customizations in `style.colors` overrides the color for this specific element.

**Comment by zamzterz** [comment]
Sorry for the confusion! There was supposed to be a "not" there: that is currently **not** supported. 🙂
