### ISSUE TITLE
Error when user tries to verify email from desktop after signing up on mobile

### ISSUE THREAD

**Issue by mela124** [schibsted/account-sdk-ios#44]
I am not sure if this is on our end but just making sure this bug is logged somewhere first

Scenario:
1. Create account on mobile app (Aftonbladet)
2. Click verification email from desktop (on the same browser, another account is logged in, different from the newly created account)
3. You will get an Invalid code error

I tried testing the same scenario on old sdk (VG) and it was working as expected. I tried testing this on the Example/Demo App, it was okay too.

**Comment by aliak00** [comment]
This is probably a web related issue. I just tried now and after clicking on the desktop I get:

![image](https://user-images.githubusercontent.com/2638284/45342498-76f49200-b59e-11e8-8565-2dc30d82f4bb.png)
