### ISSUE TITLE
Show a screen about changes in data privacy

### ISSUE THREAD

**Issue by mela124** [schibsted/account-sdk-ios#56]
Design:
https://app.zeplin.io/project/5ad8456d755b8f2e0da01dcc/screen/5ad84fe09e46a4341c0a257e
Full text: https://app.zeplin.io/project/5ad8456d755b8f2e0da01dcc/screen/5ad85a279e46a4341c0a92c0

Note: Disregard header, no changes on iOS header.

Acceptance criteria:

-It should only be shown once to the user (we can also do it once by platform. ie they can see it on all platforms they log in to)
-It is always shown before the terms of use page (sign up, login and no terms has been accept yet, updated terms) - it's a combo with terms of use page
-Continue button is enabled by default
-Continue button is sticky at the bottom of the screen. User can scroll through the text
- On press of Continue, go to the terms screen
-Back and exit controls should be consistent behaviour as rest the of the screens. In case of updated terms, this is considered as the 1st screen so just the "X" button

Note: disregard the link at the end of the screen first, we will create separate task to add all links once they are ready

**Comment by lrossi** [comment]
@mela124 In case of updated terms, does the automatic logout apply to this screen as well if the user closes it? If so, do we provide some kind of message?

**Comment by mela124** [comment]
Hello! Good question, no, if they close this page they will still be logged in but the terms page will show up next if there’s terms to be accepted.

**Comment by lrossi** [comment]
Do you mean an additional modal screen with just the terms should show up straight away in case this one is closed? Or is it ok to show the terms next time the app is launched?

Or maybe, if this is just an info alert with no action involved, we could avoid canceling and only have a `Continue` button so that the terms screen is always pushed next, and then that screen has a cancel button. What do you think?

**Comment by mela124** [comment]
We will no longer need this screen. There is no need for do this task anymore. I will close.
