### ISSUE TITLE
Update Pulse tracking for GDPR Transparency changes

### ISSUE THREAD

**Issue by mela124** [schibsted/account-sdk-ios#61]
https://github.schibsted.io/spt-dataanalytics/pulse-monitor-ui/pull/463 -- new screens, links etc

**Comment by mela124** [comment]
Currently, objectid for the What's Schibsted account is showing as:

sdrn:schibsted-account:content:identity_sdk:element:What's Schibsted account

instead of sdrn:schibsted-account:content:element:about_sch_account

**Comment by aliak00** [comment]
See #113
