### ISSUE TITLE
Refreshing spid token causes it's scope to be empty

### ISSUE THREAD

**Issue by krzysiekSzklarski** [schibsted/account-sdk-ios#68]
When the spid token is refreshed it's scope doesn't retain it's scope value, it is set to empty/nil.

My guess is that the issue is in User.refresh(completion: @escaping NoValueCallback) function in the  invocation of self.api.requestAccessToken(clientID: self.clientConfiguration.clientID, clientSecret: self.clientConfiguration.clientSecret, grantType: .refreshToken, refreshToken: tokens.refreshToken). Method is called with the default value of scope which is nil which I think causes backend to set it to nil for refreshed token.

**Comment by aliak00** [comment]
Cannot reproduce this. If there're scopes set on the access token, and a refresh request happens, it comes back with the same scopes. Will close for now and feel free to reopen if you reproduce it :)
